language: java

sudo: false

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

env:
  # - GWT_VERSION=2.8.0-beta1
  - GWT_VERSION=2.7.0
  - GWT_VERSION=2.5.1
  
script: mvn install -Dgwt.version=$GWT_VERSION
matrix:
  include:
    - jdk: openjdk7
      script: cd restygwt; mvn verify -Prun-its -Dmaven.test.skip -Dinvoker.test=restygwt-overlay-example
    - jdk: oraclejdk7
      script: cd restygwt; mvn verify -Prun-its -Dmaven.test.skip -Dinvoker.test=restygwt-rails-*
    - jdk: oraclejdk8
      script: cd restygwt; mvn verify -Prun-its -Dmaven.test.skip -Dinvoker.test=restygwt-example
    - jdk: oraclejdk8
      script: cd restygwt; mvn verify -Prun-its -Dmaven.test.skip -Dinvoker.test=restygwt-jersey-*,restygwt-cxf-jaxson-*

